### ISSUE TITLE
Add support for external realms to `ftl-project.toml`

### ISSUE THREAD

**Issue by jvmakine** [block/ftl#5280]
We should record the location of the external schema (git coordinates) to fetch the schema to the file. And add command for

```
ftl realm add --git-repo=git@github.com:bank/accounts.git --git-branch=main
```

This should add the external realm in `ftl-project.toml` like this

```toml
[external-realms.accounts]
  git-repo = "git@github.com:bank/accounts.git"
  git-branch = "main"
  git-commit = "aac675450010d2b8fc0528239e49e56fd94b5309"
  ...
```

For now, we only support importing from `protojson` format to avoid making our internal schema representation backwards compatible.

Note: this deviates a bit from the design doc, where we had an `[egress]` block. Wether realm is egress, ingress, or both, can be deduced from the schema itself.
